apiVersion: v1
kind: Secret
metadata:
  name: bucket-secrets
  namespace: object-monitor
type: Opaque
stringData:
  # Base64 encoded bucket config
  # IMPORTANT: Replace this example with your actual buckets in production
  buckets.yaml: |
    buckets:
      - name: "harmonic-sea"
        access_key: "xxxxxx"
        secret_key: "xxxxxx"
        endpoint: "us-sea-1.linodeobjects.com"
      
      - name: "harmonic-ord"
        access_key: "xxxxxx"
        secret_key: "xxxxxx"
        endpoint: "us-ord-1.linodeobjects.com"
      
      - name: "harmonic-iad"
        access_key: "xxxxxx"
        secret_key: "xxxxxx"
        endpoint: "us-iad-1.linodeobjects.com"

      - name: "data-sync-tool"
        access_key: "xxxxxx"
        secret_key: "xxxxxx"
        endpoint: "us-ord-1.linodeobjects.com"

      - name: "disney-test-bucket"
        access_key: "xxxxxx"
        secret_key: "xxxxxx"
        endpoint: "us-ord-1.linodeobjects.com"

      - name: "disney-test-bucket-2"
        access_key: "xxxxxx"
        secret_key: "xxxxxx"
        endpoint: "us-ord-1.linodeobjects.com"

      - name: "harmonic-west-bucket"
        access_key: "xxxxxx"
        secret_key: "xxxxxx"
        endpoint: "us-sea-1.linodeobjects.com"
      
      - name: "lifecylce-policy"
        access_key: "xxxxxx"
        secret_key: "xxxxxx"
        endpoint: "us-ord-1.linodeobjects.com"
      
      - name: "ns-object-migration"
        access_key: "xxxxxx"
        secret_key: "xxxxxx"
        endpoint: "us-ord-1.linodeobjects.com"
      
      - name: "obj-notification-bucket-1"
        access_key: "xxxxxx"
        secret_key: "xxxxxx"
        endpoint: "us-ord-1.linodeobjects.com"

      - name: "obj-notification-bucket-2"
        access_key: "xxxxxx"
        secret_key: "xxxxxx"
        endpoint: "us-ord-1.linodeobjects.com"

      - name: "test-bucket-1"
        access_key: "xxxxxx"
        secret_key: "xxxxxx"
        endpoint: "us-ord-1.linodeobjects.com"
      
      - name: "test-bucket-2"
        access_key: "xxxxxx"
        secret_key: "xxxxxx"
        endpoint: "us-ord-1.linodeobjects.com"
      
      - name: "test-bucket-33"
        access_key: "xxxxxx"
        secret_key: "xxxxxx"
        endpoint: "us-ord-1.linodeobjects.com"
      
      - name: "test-bucket-4"
        access_key: "xxxxxx"
        secret_key: "xxxxxx"
        endpoint: "us-ord-1.linodeobjects.com"
      
      - name: "test-bucket-5"
        access_key: "xxxxxx"
        secret_key: "xxxxxx"
        endpoint: "us-ord-1.linodeobjects.com"

      - name: "tf-lke-bucket"
        access_key: "xxxxxx"
        secret_key: "xxxxxx"
        endpoint: "us-iad-1.linodeobjects.com"
      
  
  webhook-url: "https://webhook.site/c74aeff2-270c-4d3d-8fed-a0d2fea46622"
