apiVersion: v1
kind: Secret
metadata:
  name: bucket-secrets
  namespace: object-monitor
type: Opaque
stringData:
  # Base64 encoded bucket config
  # IMPORTANT: Replace this example with your actual buckets in production
  buckets.yaml: |
    buckets:
      # Region 1 buckets
      - name: "bucket-1"
        access_key: "ACCESS_KEY_1"
        secret_key: "SECRET_KEY_1"
        endpoint: "us-east-1.linodeobjects.com"
      
      - name: "bucket-2"
        access_key: "ACCESS_KEY_2"
        secret_key: "SECRET_KEY_2"
        endpoint: "us-east-1.linodeobjects.com"
      
      # Region 2 buckets
      - name: "bucket-3"
        access_key: "ACCESS_KEY_3"
        secret_key: "SECRET_KEY_3"
        endpoint: "eu-central-1.linodeobjects.com"
      
      # Add all your buckets here
      # For hundreds of buckets, consider generating this file programmatically
  
  webhook-url: "https://your-webhook-endpoint.com"
