apiVersion: v1
kind: Service
metadata:
  name: loki-proxy-lb
  namespace: monitoring
  labels:
    app: loki
  annotations:
spec:
  type: LoadBalancer
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP
      name: http-loki
  selector:
    app: loki-proxy  
